### ISSUE TITLE
Somebody cloned this repo and uploaded on Evanto

### ISSUE THREAD

**Issue by jfkdcman** [DineshNeupane/nCOVIDroid#1]
Some spammers just cloned this repository and uploaded in Codecanyon. Please take action against it. Here is the link: https://codecanyon.net/item/corona-virus-real-time-tracker-with-admob-support-to-make-money-through-app-coronacash/25947385

**Comment by DineshNeupane** [comment]
@glen978 Please double check and confirm before making your claims. You can always compare the creation/published date if you are not dumb enough to realize this. 
Published/Created date on the link you've mentioned:
![sc_1](https://user-images.githubusercontent.com/19649670/76531849-e56d2580-649d-11ea-8815-89984cbb742d.PNG)

This project publication date: (5 March 2020)
![screenshot_2](https://user-images.githubusercontent.com/19649670/76532195-60364080-649e-11ea-8323-e74c4507ab1c.PNG)

It's a open source project I initiated under GPL v3  Licence. So, basically you can modify and use it commercially as long as you mention the source of the code and publish your modifications under same licence. If anybody is not aligned with the terms of the licence I will take action against it. Thanks.

**Comment by glen978** [comment]
They submit there for weeks before it's approved on the date you see.

No worries tho 👍

**Comment by DineshNeupane** [comment]
@glen978 don't come here to open issues with this kind of baseless claims, it's the project I developed to test my knowledge with live data. you are welcome if you can contribute to it, otherwise you can just fuck off.

**Comment by glen978** [comment]
its nothing.. i said i am your firend if you want...  So no need to insult
me for anything.... its nothing
